### ISSUE TITLE
Error happend in the example dataset.

### ISSUE THREAD

**Issue by youlongjizi** [mglev1n/locusplotr#2]
Extracting LD for 16:53830055_C/G for the region 16:53580059-54079197
Error in `right_join()`:
! `...` must be empty.
✖ Problematic argument:
• relationship = "many-to-many"
Run `rlang::last_trace()` to see where the error occurred.

**Comment by mglev1n** [comment]
Please provide a reproducible example (https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) - currently all the package tests and examples on the github page appear to run correctly for me. Without seeing the command you're trying to run, it's hard to provide any advice.
