### ISSUE TITLE
Error in `ld_extract_locuszoom()`: ! Reference variant is missing from the specified LD panel when running "ld_extract_locuszoom" function

### ISSUE THREAD

**Issue by amingjie228** [mglev1n/locusplotr#4]
When I run "ld_extract_locuszoom" function, I encounter this error. However, the example data can provide the corresponding results.
> ld_extract_locuszoom(chrom = 10, pos = 46044649, ref = "G", alt = "A", start = 46033307  - 5e4, stop = 46048180  + 5e4, genome_build = "GRCh38", population = "ALL", metric = "rsquare")
ℹ Extracting LD for 10:46044649_G/A for the region 10:45983307-46098180
ℹ Initial query failed - trying again with flipped Ref/Alt
Error in `ld_extract_locuszoom()`:
! Reference variant is missing from the specified LD panel

and  this is my data:
> head(MSMB)
   chromosome position         rsid effect_allele other_allele     eaf  effect  std_err   p_value
1:         10 45983346   rs71257889             C            G 0.41760 -0.0238 0.008481 5.014e-03
2:         10 45983869   rs71277324             A            G 0.26269 -0.1199 0.009453 7.279e-37
3:         10 45983944   rs61849500             A            G 0.00399  0.3462 0.064763 9.010e-08
4:         10 45983949 rs1411783984             T            G 0.00355  0.2657 0.068827 1.132e-04
5:         10 45984066 rs1325250454             T            G 0.01791 -0.1826 0.030796 3.040e-09
6:         10 45984211 rs1213672813             C            T 0.00037  0.4462 0.224149 4.652e-02

**Comment by mglev1n** [comment]
The variant that you're trying to query (`10:46044649:G:A`) doesn't exist in the reference panel. If you look up that variant in gnomAD, it doesn't seem to exist in either GRCh38 (or GRCh37): https://gnomad.broadinstitute.org/variant/10-46044649-G-A. The function queries the University of Michigan LocusZoom API, which serves information from the 1000 Genomes reference panels: https://portaldev.sph.umich.edu/docs/api/v1/#introduction
